apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec: #especificação do replicaset
  replicas: 9
  selector:
    matchLabels: #quais pods ira gerenciatr
      app: api #esse aqui
  template:
    metadata:
      labels: 
        app: api #eh igual a esse aqui
    spec: #espicificação do pod
      containers:
        - name: api
          image: brunopa/k8s:v1 #kubernet se usa do dockerhub eh isso mesmo?
          ports:
            - containerPort: 8080 
          env:
            - name: MONGODB_URI
              value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin
