apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec: #especificação do replicaset
  replicas: 1
  selector:
    matchLabels: #quais pods ira gerenciatr
      app: api #esse aqui
  template:
    metadata:
      labels: 
        app: api #eh igual a esse aqui
    spec: #espicificação do pod
      containers:
        - name: api
          image: brunopa/k8s:v1
          ports:
            - containerPort: 8080 
          env:
            - name: MONGODB_URI
              value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin

---

apiVersion: v1
kind: Service
metadata:
  name: api-service

spec: #especificação do replicaset
  selector:
    app: api #esse aqui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort