apiVersion: v1
kind: Service
metadata:
  name: api-service

spec: #especificação do replicaset
  selector:
    app: api #esse aqui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer # por estar na nuvem